#!/usr/bin/busybox sh

/usr/bin/busybox mount -t devtmpfs devtmpfs /dev
/usr/bin/busybox mount -t proc none /proc
/usr/bin/busybox mount -t sysfs none /sys
# for 9p fs
/usr/bin/busybox modprobe virtio_pci
/usr/bin/busybox modprobe 9p
/usr/bin/busybox modprobe 9pnet_virtio
/usr/bin/busybox mount -t 9p rootshare /mnt/root -o trans=virtio,version=9p2000.L
exec /usr/bin/busybox switch_root /mnt/root /sbin/init
