#!/usr/bin/busybox sh
/usr/bin/busybox mount -t devtmpfs devtmpfs /dev
/usr/bin/busybox mount -t proc none /proc
/usr/bin/busybox mount -t sysfs none /sys
# for tcpdump
/usr/bin/busybox modprobe af_packet
/usr/bin/busybox modprobe unix

# for eth0 interface
/usr/bin/busybox modprobe e1000

/usr/bin/busybox modprobe ipv6

/usr/bin/busybox ip l set lo up
/usr/bin/busybox ip l set eth0 up

export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
exec /usr/bin/busybox getty -n 115200 ttyS0 -l /usr/bin/bash vt100
